name: Build EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Install PySide6
      run: pip install PySide6

    - name: Install APScheduler
      run: pip install APScheduler

    - name: Install chardet
      run: pip install chardet

    - name: Install python-dateutil
      run: pip install python-dateutil

    - name: Build
      run: pyinstaller --onefile --windowed main.py

    - uses: actions/upload-artifact@v4
      with:
        name: EXE
        path: dist/main.exe