name: Build

on: [push, workflow_dispatch]

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: pip install pyinstaller PySide6 APScheduler chardet python-dateutil
    
    - name: Build EXE
      run: pyinstaller --onefile --windowed --name=WindowsTaskScheduler main.py
    
    - uses: actions/upload-artifact@v4
      with:
        name: WindowsTaskScheduler-EXE
        path: dist\WindowsTaskScheduler.exe